// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "ziyun/opstring-service/pb"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	HealthEndpoint   endpoint.Endpoint
	OpstringEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) Health(ctx context.Context, in *pb.HealthRequest) (*pb.HealthResponse, error) {
	response, err := e.HealthEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.HealthResponse), nil
}

func (e Endpoints) Opstring(ctx context.Context, in *pb.OpstringRequest) (*pb.OpstringResponse, error) {
	response, err := e.OpstringEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.OpstringResponse), nil
}

// Make Endpoints

func MakeHealthEndpoint(s pb.OpstringServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.HealthRequest)
		v, err := s.Health(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeOpstringEndpoint(s pb.OpstringServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.OpstringRequest)
		v, err := s.Opstring(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"Health":   {},
		"Opstring": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "Health" {
			e.HealthEndpoint = middleware(e.HealthEndpoint)
		}
		if inc == "Opstring" {
			e.OpstringEndpoint = middleware(e.OpstringEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"Health":   {},
		"Opstring": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "Health" {
			e.HealthEndpoint = middleware("Health", e.HealthEndpoint)
		}
		if inc == "Opstring" {
			e.OpstringEndpoint = middleware("Opstring", e.OpstringEndpoint)
		}
	}
}
