// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package main

import (
	// This Service
	"ziyun/auth-service/svc/server"
)

// curl -X POST "http://192.168.73.3:5150/auth/Token" -H "Content-Type: application/json" --data '{"CompanyID":"1", "UserName":"xuheng", "Passwd":"123456"}'
//curl -X POST "http://192.168.73.3:5150/auth/Refresh_Token" -H "Content-Type: application/json" --data '{"RToken":"Q2xpZW50SWRfVXNlcklkXzE2MDEyMDgyOTU="}'
//curl -X POST "http://192.168.73.3:5150/auth/Check_Token" -H "Content-Type: application/json" --data '{"AToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDEzODgxODIsImlzcyI6IlN5c3RlbSIsIkNsaWVudCI6eyJDbGllbnRJZCI6IkNsaWVudElkIiwiQ2xpZW50U2VjcmV0IjoiIiwiQWNjZXNzVG9rZW5WYWxpZGl0eVNlY29uZHMiOjg2NDAwLCJSZWZyZXNoVG9rZW5WYWxpZGl0eVNlY29uZHMiOjI1OTIwMDAsIlJlZ2lzdGVyZWRSZWRpcmVjdFVyaSI6IiIsIkF1dGhvcml6ZWRHcmFudFR5cGVzIjpudWxsfSwiVXNlciI6eyJVc2VySWQiOiJVc2VySWQiLCJVc2VybmFtZSI6IlVzZXJuYW1lIiwiUGFzc3dvcmQiOiIiLCJBdXRob3JpdGllcyI6bnVsbH19.mqc5I2Pm-uftpkK6l7ktb-47g_l3eRvXloQTdIfvYEU"}'

func main() {
	// Update addresses if they have been overwritten by flags
	//flag.Parse()

	server.Run()
}
