// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opstring.proto

// The package name determines the name of the directories that truss creates
// for `package operate;` truss will create the directory "operate-service".

package opstring

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/metaverse/truss/deftree/googlethirdparty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type HealthRequest struct {
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85f3f83b6822e1b, []int{0}
}
func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return m.Size()
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	Status bool `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85f3f83b6822e1b, []int{1}
}
func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return m.Size()
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type OpstringRequest struct {
	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	A    string `protobuf:"bytes,2,opt,name=A,proto3" json:"A,omitempty"`
	B    string `protobuf:"bytes,3,opt,name=B,proto3" json:"B,omitempty"`
}

func (m *OpstringRequest) Reset()         { *m = OpstringRequest{} }
func (m *OpstringRequest) String() string { return proto.CompactTextString(m) }
func (*OpstringRequest) ProtoMessage()    {}
func (*OpstringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85f3f83b6822e1b, []int{2}
}
func (m *OpstringRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpstringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpstringRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OpstringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpstringRequest.Merge(m, src)
}
func (m *OpstringRequest) XXX_Size() int {
	return m.Size()
}
func (m *OpstringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpstringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpstringRequest proto.InternalMessageInfo

func (m *OpstringRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OpstringRequest) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *OpstringRequest) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

type OpstringResponse struct {
	Out string `protobuf:"bytes,1,opt,name=Out,proto3" json:"Out,omitempty"`
}

func (m *OpstringResponse) Reset()         { *m = OpstringResponse{} }
func (m *OpstringResponse) String() string { return proto.CompactTextString(m) }
func (*OpstringResponse) ProtoMessage()    {}
func (*OpstringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85f3f83b6822e1b, []int{3}
}
func (m *OpstringResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpstringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpstringResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OpstringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpstringResponse.Merge(m, src)
}
func (m *OpstringResponse) XXX_Size() int {
	return m.Size()
}
func (m *OpstringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpstringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpstringResponse proto.InternalMessageInfo

func (m *OpstringResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "opstring.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "opstring.HealthResponse")
	proto.RegisterType((*OpstringRequest)(nil), "opstring.OpstringRequest")
	proto.RegisterType((*OpstringResponse)(nil), "opstring.OpstringResponse")
}

func init() { proto.RegisterFile("opstring.proto", fileDescriptor_e85f3f83b6822e1b) }

var fileDescriptor_e85f3f83b6822e1b = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xbb, 0xad, 0xd4, 0x38, 0x68, 0x5b, 0x16, 0xaa, 0x31, 0x42, 0x90, 0xe0, 0xa1, 0x78,
	0xe8, 0x82, 0xde, 0xbc, 0xb5, 0x20, 0x78, 0x2b, 0x54, 0x0f, 0xc5, 0x5b, 0x6a, 0xc7, 0x24, 0xd0,
	0x66, 0xe3, 0xee, 0x44, 0x28, 0xe2, 0xc5, 0x27, 0x10, 0x7c, 0x1f, 0xcf, 0x1e, 0x0b, 0x5e, 0x3c,
	0x4a, 0xeb, 0x83, 0x48, 0x93, 0x8d, 0xf5, 0xdf, 0x6d, 0xbe, 0xf9, 0x26, 0xbf, 0x99, 0x2f, 0x0b,
	0x35, 0x99, 0x68, 0x52, 0x51, 0x1c, 0xb4, 0x13, 0x25, 0x49, 0x72, 0xab, 0xd0, 0xce, 0x69, 0x10,
	0x51, 0x98, 0x0e, 0xdb, 0x57, 0x72, 0x22, 0x26, 0x48, 0xfe, 0x2d, 0x2a, 0x8d, 0x82, 0x54, 0xaa,
	0xb5, 0x18, 0xe1, 0x35, 0x29, 0x44, 0x11, 0x48, 0x19, 0x8c, 0x91, 0xc2, 0x48, 0x8d, 0x12, 0x5f,
	0xd1, 0x54, 0xf8, 0x71, 0x2c, 0xc9, 0xa7, 0x48, 0xc6, 0x3a, 0x07, 0x7a, 0x75, 0xd8, 0x3a, 0x43,
	0x7f, 0x4c, 0x61, 0x1f, 0x6f, 0x52, 0xd4, 0xe4, 0xb5, 0xa0, 0x56, 0x34, 0x74, 0x22, 0x63, 0x8d,
	0x7c, 0x1b, 0xaa, 0xe7, 0xe4, 0x53, 0xaa, 0x6d, 0xb6, 0xcf, 0x5a, 0x56, 0xdf, 0x28, 0xaf, 0x03,
	0xf5, 0x9e, 0xb9, 0xc6, 0x7c, 0xcc, 0x39, 0xac, 0x5d, 0x4c, 0x13, 0xcc, 0x06, 0x37, 0xfa, 0x59,
	0xcd, 0x37, 0x81, 0x75, 0xec, 0x72, 0xd6, 0x60, 0x9d, 0xa5, 0xea, 0xda, 0x95, 0x5c, 0x75, 0xbd,
	0x03, 0x68, 0xac, 0x10, 0x66, 0x5d, 0x03, 0x2a, 0xbd, 0x94, 0x0c, 0x62, 0x59, 0x1e, 0x3d, 0x33,
	0xb0, 0x8a, 0x31, 0x3e, 0x80, 0x6a, 0x7e, 0x1f, 0xdf, 0x69, 0x7f, 0xfd, 0x9c, 0x1f, 0x11, 0x1c,
	0xfb, 0xaf, 0x91, 0xb3, 0xbd, 0xbd, 0x87, 0xd7, 0x8f, 0xa7, 0x72, 0x93, 0xaf, 0x8b, 0x30, 0x33,
	0x2e, 0x81, 0x5b, 0xa6, 0x14, 0x7c, 0xf0, 0x6d, 0xcb, 0xee, 0x0a, 0xf1, 0x2b, 0xa3, 0xe3, 0xfc,
	0x67, 0x19, 0x7e, 0x33, 0xe3, 0xd7, 0x3d, 0x10, 0x32, 0x11, 0x77, 0xcb, 0xf8, 0xf7, 0x27, 0xec,
	0xb0, 0x6b, 0xbf, 0xcc, 0x5d, 0x36, 0x9b, 0xbb, 0xec, 0x7d, 0xee, 0xb2, 0xc7, 0x85, 0x5b, 0x9a,
	0x2d, 0xdc, 0xd2, 0xdb, 0xc2, 0x2d, 0x0d, 0xab, 0xd9, 0x2b, 0x1c, 0x7f, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x75, 0x4a, 0x93, 0xe8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpstringClient is the client API for Opstring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpstringClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Opstring(ctx context.Context, in *OpstringRequest, opts ...grpc.CallOption) (*OpstringResponse, error)
}

type opstringClient struct {
	cc *grpc.ClientConn
}

func NewOpstringClient(cc *grpc.ClientConn) OpstringClient {
	return &opstringClient{cc}
}

func (c *opstringClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/opstring.Opstring/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opstringClient) Opstring(ctx context.Context, in *OpstringRequest, opts ...grpc.CallOption) (*OpstringResponse, error) {
	out := new(OpstringResponse)
	err := c.cc.Invoke(ctx, "/opstring.Opstring/Opstring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpstringServer is the server API for Opstring service.
type OpstringServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Opstring(context.Context, *OpstringRequest) (*OpstringResponse, error)
}

// UnimplementedOpstringServer can be embedded to have forward compatible implementations.
type UnimplementedOpstringServer struct {
}

func (*UnimplementedOpstringServer) Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (*UnimplementedOpstringServer) Opstring(ctx context.Context, req *OpstringRequest) (*OpstringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Opstring not implemented")
}

func RegisterOpstringServer(s *grpc.Server, srv OpstringServer) {
	s.RegisterService(&_Opstring_serviceDesc, srv)
}

func _Opstring_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpstringServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opstring.Opstring/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpstringServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Opstring_Opstring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpstringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpstringServer).Opstring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opstring.Opstring/Opstring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpstringServer).Opstring(ctx, req.(*OpstringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Opstring_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opstring.Opstring",
	HandlerType: (*OpstringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Opstring_Health_Handler,
		},
		{
			MethodName: "Opstring",
			Handler:    _Opstring_Opstring_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opstring.proto",
}

func (m *HealthRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HealthRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *HealthResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HealthResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status {
		dAtA[i] = 0x8
		i++
		if m.Status {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *OpstringRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpstringRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOpstring(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.A) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOpstring(dAtA, i, uint64(len(m.A)))
		i += copy(dAtA[i:], m.A)
	}
	if len(m.B) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOpstring(dAtA, i, uint64(len(m.B)))
		i += copy(dAtA[i:], m.B)
	}
	return i, nil
}

func (m *OpstringResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpstringResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Out) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOpstring(dAtA, i, uint64(len(m.Out)))
		i += copy(dAtA[i:], m.Out)
	}
	return i, nil
}

func encodeVarintOpstring(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *HealthRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *HealthResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status {
		n += 2
	}
	return n
}

func (m *OpstringRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovOpstring(uint64(l))
	}
	l = len(m.A)
	if l > 0 {
		n += 1 + l + sovOpstring(uint64(l))
	}
	l = len(m.B)
	if l > 0 {
		n += 1 + l + sovOpstring(uint64(l))
	}
	return n
}

func (m *OpstringResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Out)
	if l > 0 {
		n += 1 + l + sovOpstring(uint64(l))
	}
	return n
}

func sovOpstring(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOpstring(x uint64) (n int) {
	return sovOpstring(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HealthRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpstring
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HealthRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HealthRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipOpstring(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HealthResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpstring
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HealthResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HealthResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipOpstring(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpstringRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpstring
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpstringRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpstringRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpstring
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpstring
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpstring
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpstring
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.A = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpstring
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpstring
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.B = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpstring(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpstringResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpstring
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpstringResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpstringResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Out", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpstring
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpstring
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Out = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpstring(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOpstring
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOpstring(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOpstring
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpstring
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOpstring
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthOpstring
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOpstring
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOpstring(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthOpstring
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOpstring = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOpstring   = fmt.Errorf("proto: integer overflow")
)
