// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "ziyun/auth-service/pb"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC AuthServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.AuthServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// auth

		health: grpctransport.NewServer(
			endpoints.HealthEndpoint,
			DecodeGRPCHealthRequest,
			EncodeGRPCHealthResponse,
			serverOptions...,
		),
		auth: grpctransport.NewServer(
			endpoints.AuthEndpoint,
			DecodeGRPCAuthRequest,
			EncodeGRPCAuthResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the AuthServer interface
type grpcServer struct {
	health grpctransport.Handler
	auth   grpctransport.Handler
}

// Methods for grpcServer to implement AuthServer interface

func (s *grpcServer) Health(ctx context.Context, req *pb.HealthRequest) (*pb.HealthResponse, error) {
	_, rep, err := s.health.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.HealthResponse), nil
}

func (s *grpcServer) Auth(ctx context.Context, req *pb.AuthRequest) (*pb.AuthResponse, error) {
	_, rep, err := s.auth.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.AuthResponse), nil
}

// Server Decode

// DecodeGRPCHealthRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC health request to a user-domain health request. Primarily useful in a server.
func DecodeGRPCHealthRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.HealthRequest)
	return req, nil
}

// DecodeGRPCAuthRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC auth request to a user-domain auth request. Primarily useful in a server.
func DecodeGRPCAuthRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.AuthRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCHealthResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain health response to a gRPC health reply. Primarily useful in a server.
func EncodeGRPCHealthResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.HealthResponse)
	return resp, nil
}

// EncodeGRPCAuthResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain auth response to a gRPC auth reply. Primarily useful in a server.
func EncodeGRPCAuthResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.AuthResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
