// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package server

import (
	"log"
	"net"
	"net/http"
	"strconv"
	"ziyun/auth-service/token"
	"ziyun/util/consul"

	// 3d Party
	"google.golang.org/grpc"

	"ziyun/auth-service/handlers"
	// This Service
	pb "ziyun/auth-service/pb"
	"ziyun/auth-service/svc"
	"ziyun/util/bootstrap"
	"ziyun/util/mysql"
	"ziyun/util/redis"
)

func NewEndpoints(service pb.AuthServer) svc.Endpoints {
	// Business domain.

	// Wrap Service with middlewares. See handlers/middlewares.go
	service = handlers.WrapService(service)

	// Endpoint domain.
	var (
		healthEndpoint = svc.MakeHealthEndpoint(service)
		authEndpoint   = svc.MakeAuthEndpoint(service)
	)

	endpoints := svc.Endpoints{
		HealthEndpoint: healthEndpoint,
		AuthEndpoint:   authEndpoint,
	}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = handlers.WrapEndpoints(endpoints)

	return endpoints
}

func GetDockerIp() ([]string, error) {
	addrs, err := net.InterfaceAddrs()

	if err != nil {
		return nil, err
	}

	var host []string
	for _, address := range addrs {
		// 检查ip地址判断是否回环地址
		if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			if ipnet.IP.To4() != nil {
				host = append(host, ipnet.IP.String())
			}
		}
	}

	return host, nil
}

// Run starts a new http server, gRPC server, and a debug server with the
// passed config and logger
func Run() {
	service := handlers.NewService()
	endpoints := NewEndpoints(service)

	//在docker中运行，配置文件不需要配置host，自动获取docker的地址
	if bootstrap.HttpConfig.Host == "" || bootstrap.RpcConfig.Host == "" {
		dockerips, err := GetDockerIp()
		if err != nil {
			log.Fatal("Fail to get docker address", err)
		}
		bootstrap.HttpConfig.Host = dockerips[0]
		bootstrap.RpcConfig.Host = dockerips[0]
	}

	//注册到consul
	consul.Register()

	//初始化redis
	redis.InitRedis(bootstrap.Redisconfig.ClusterIPs, bootstrap.Redisconfig.PoolSize,
		bootstrap.Redisconfig.MinIdleConns, bootstrap.Redisconfig.Password)

	//初始化mysql
	mysql.InitMysql(bootstrap.Mysqlconfig.DbUser, bootstrap.Mysqlconfig.DbPassword,
		bootstrap.Mysqlconfig.DbHost, bootstrap.Mysqlconfig.DbName, bootstrap.Mysqlconfig.DbPort,
		bootstrap.Mysqlconfig.MaxIdleConns, bootstrap.Mysqlconfig.MaxOpenConns, bootstrap.Mysqlconfig.ConnMaxLifetime)

	//初始化jwt密码
	token.InitJwtToken(bootstrap.JwtConfig.JwtSecretKey)

	// Mechanical domain.
	errc := make(chan error)

	// Interrupt handler.
	go handlers.InterruptHandler(errc)

	// Debug listener.
	//go func() {
	//	log.Println("transport", "debug", "addr", cfg.DebugAddr)
	//
	//	m := http.NewServeMux()
	//	m.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
	//	m.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
	//	m.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
	//	m.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
	//	m.Handle("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))
	//
	//	errc <- http.ListenAndServe(cfg.DebugAddr, m)
	//}()

	// HTTP transport.
	go func() {
		log.Println("transport", "HTTP", "addr", bootstrap.HttpConfig.Host, bootstrap.HttpConfig.Port)
		addr := bootstrap.HttpConfig.Host + ":" + strconv.Itoa(bootstrap.HttpConfig.Port)
		h := svc.MakeHTTPHandler(endpoints)
		errc <- http.ListenAndServe(addr, h)
	}()

	// gRPC transport.
	go func() {
		log.Println("transport", "gRPC", "addr", bootstrap.RpcConfig.Host, bootstrap.RpcConfig.Port)
		addr := bootstrap.RpcConfig.Host + ":" + strconv.Itoa(bootstrap.RpcConfig.Port)
		ln, err := net.Listen("tcp", addr)
		if err != nil {
			errc <- err
			return
		}

		srv := svc.MakeGRPCServer(endpoints)
		s := grpc.NewServer()
		pb.RegisterAuthServer(s, srv)

		errc <- s.Serve(ln)
	}()

	// Run!
	log.Println("exit", <-errc)
	consul.Deregister()
}
