// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

// Package grpc provides a gRPC client for the Auth service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "ziyun/auth-service/pb"
	"ziyun/auth-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.AuthServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var healthEndpoint endpoint.Endpoint
	{
		healthEndpoint = grpctransport.NewClient(
			conn,
			"auth.Auth",
			"Health",
			EncodeGRPCHealthRequest,
			DecodeGRPCHealthResponse,
			pb.HealthResponse{},
			clientOptions...,
		).Endpoint()
	}

	var authEndpoint endpoint.Endpoint
	{
		authEndpoint = grpctransport.NewClient(
			conn,
			"auth.Auth",
			"Auth",
			EncodeGRPCAuthRequest,
			DecodeGRPCAuthResponse,
			pb.AuthResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		HealthEndpoint: healthEndpoint,
		AuthEndpoint:   authEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCHealthResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC health reply to a user-domain health response. Primarily useful in a client.
func DecodeGRPCHealthResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.HealthResponse)
	return reply, nil
}

// DecodeGRPCAuthResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC auth reply to a user-domain auth response. Primarily useful in a client.
func DecodeGRPCAuthResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AuthResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCHealthRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain health request to a gRPC health request. Primarily useful in a client.
func EncodeGRPCHealthRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HealthRequest)
	return req, nil
}

// EncodeGRPCAuthRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain auth request to a gRPC auth request. Primarily useful in a client.
func EncodeGRPCAuthRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AuthRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
