// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package main

import (
	// This Service
	"ziyun/opstring-service/svc/server"
)

//curl 192.168.73.3:5250/health
//curl -X POST "http://192.168.73.3:5250/opstring/Diff" -H "Content-Type: application/json" --data '{"A":"xuheng", "B":"good"}'
func main() {
	// Update addresses if they have been overwritten by flags

	server.Run()
}
